### Cleaning Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data.csv")

In [6]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [7]:
print('''
VTAT- Vehicle time at arrival
CTAT- Customer time at arrival
''')

VTAT- Vehicle time at arrival
CTAT- Customer time at arrival

In [4]:
df.dtypes

Date                                  object
Time                                  object
Booking ID                            object
Booking Status                        object
Customer ID                           object
Vehicle Type                          object
Pickup Location                       object
Drop Location                         object
Avg VTAT                             float64
Avg CTAT                             float64
Cancelled Rides by Customer          float64
Reason for cancelling by Customer     object
Cancelled Rides by Driver            float64
Driver Cancellation Reason            object
Incomplete Rides                     float64
Incomplete Rides Reason               object
Booking Value                        float64
Ride Distance                        float64
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                        object
dtype: object

In [8]:
df.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,10500.0,27000.0,9000.0,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,1.0,1.0,1.0,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,0.0,0.0,0.0,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,1.0,1.0,1.0,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,1.0,1.0,1.0,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,1.0,1.0,1.0,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,1.0,1.0,1.0,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,1.0,1.0,1.0,4277.000000,50.000000,5.000000,5.000000

Changing date and time from object to datetime

In [12]:
#changing data types
df['Dates'] = pd.to_datetime(df['Date'])
df['xTime'] = pd.to_datetime(df['Time'])

C:\Users\Mahadevan\AppData\Local\Temp\ipykernel_32576\66524009.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['xTime'] = pd.to_datetime(df['Time'])

In [13]:
df.dtypes

Date                                         object
Time                                         object
Booking ID                                   object
Booking Status                               object
Customer ID                                  object
Vehicle Type                                 object
Pickup Location                              object
Drop Location                                object
Avg VTAT                                    float64
Avg CTAT                                    float64
Cancelled Rides by Customer                 float64
Reason for cancelling by Customer            object
Cancelled Rides by Driver                   float64
Driver Cancellation Reason                   object
Incomplete Rides                            float64
Incomplete Rides Reason                      object
Booking Value                               float64
Ride Distance                               float64
Driver Ratings                              float64
Customer Rating                             float64
Payment Method                               object
Dates                                datetime64[ns]
xTime                                datetime64[ns]
dtype: object

In [17]:
df.drop(['Date'], axis=1)

,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,...,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Dates,xTime
0,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-23,2025-08-16 12:29:38
1,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,...,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI,2024-11-29,2025-08-16 18:01:39
2,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,...,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card,2024-08-23,2025-08-16 08:56:10
3,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,...,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI,2024-10-21,2025-08-16 17:17:25
4,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,...,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI,2024-09-16,2025-08-16 22:08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,NaN,...,NaN,NaN,NaN,475.0,40.08,3.7,4.1,Uber Wallet,2024-11-11,2025-08-16 19:34:01
149996,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,NaN,...,NaN,NaN,NaN,1093.0,21.31,4.8,5.0,UPI,2024-11-24,2025-08-16 15:55:09
149997,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,NaN,...,NaN,NaN,NaN,852.0,15.93,3.9,4.4,Cash,2024-09-18,2025-08-16 10:55:15
149998,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,NaN,...,NaN,NaN,NaN,333.0,45.54,4.1,3.7,UPI,2024-10-05,2025-08-16 07:53:34
149999,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,NaN,...,NaN,NaN,NaN,806.0,21.19,4.6,4.9,Credit Card,2024-03-10,2025-08-16 15:38:03

In [18]:
df.drop(['Time'], axis=1)

,Date,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,...,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Dates,xTime
0,2024-03-23,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-23,2025-08-16 12:29:38
1,2024-11-29,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,...,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI,2024-11-29,2025-08-16 18:01:39
2,2024-08-23,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,...,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card,2024-08-23,2025-08-16 08:56:10
3,2024-10-21,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,...,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI,2024-10-21,2025-08-16 17:17:25
4,2024-09-16,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,...,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI,2024-09-16,2025-08-16 22:08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,NaN,...,NaN,NaN,NaN,475.0,40.08,3.7,4.1,Uber Wallet,2024-11-11,2025-08-16 19:34:01
149996,2024-11-24,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,NaN,...,NaN,NaN,NaN,1093.0,21.31,4.8,5.0,UPI,2024-11-24,2025-08-16 15:55:09
149997,2024-09-18,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,NaN,...,NaN,NaN,NaN,852.0,15.93,3.9,4.4,Cash,2024-09-18,2025-08-16 10:55:15
149998,2024-10-05,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,NaN,...,NaN,NaN,NaN,333.0,45.54,4.1,3.7,UPI,2024-10-05,2025-08-16 07:53:34
149999,2024-03-10,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,NaN,...,NaN,NaN,NaN,806.0,21.19,4.6,4.9,Credit Card,2024-03-10,2025-08-16 15:38:03

Checking Null Values

In [ ]:
df.isna()

In [36]:
df.rename(columns={'Dates':'Date', 'xTime':'Time'})

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Date,Time
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,0.0,0.0,...,NaN,0.0,Na,NaN,NaN,NaN,NaN,NaN,2024-03-23,2025-08-16 12:29:38
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI,2024-11-29,2025-08-16 18:01:39
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,0.0,Na,627.0,13.58,4.9,4.9,Debit Card,2024-08-23,2025-08-16 08:56:10
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,0.0,Na,416.0,34.02,4.6,5.0,UPI,2024-10-21,2025-08-16 17:17:25
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,0.0,Na,737.0,48.21,4.1,4.3,UPI,2024-09-16,2025-08-16 22:08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,...,NaN,0.0,Na,475.0,40.08,3.7,4.1,Uber Wallet,2024-11-11,2025-08-16 19:34:01
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,NaN,0.0,Na,1093.0,21.31,4.8,5.0,UPI,2024-11-24,2025-08-16 15:55:09
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,NaN,0.0,Na,852.0,15.93,3.9,4.4,Cash,2024-09-18,2025-08-16 10:55:15
149998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,...,NaN,0.0,Na,333.0,45.54,4.1,3.7,UPI,2024-10-05,2025-08-16 07:53:34
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,...,NaN,0.0,Na,806.0,21.19,4.6,4.9,Credit Card,2024-03-10,2025-08-16 15:38:03

In [29]:
df['Driver Cancellation Reason'].unique()

array([nan, 'Personal & Car related issues', 'Customer related issue',
       'More than permitted people in there',
       'The customer was coughing/sick'], dtype=object)

In [33]:
df['Reason for cancelling by Customer'].unique()

array([nan, 'Driver is not moving towards pickup location',
       'Driver asked to cancel', 'AC is not working', 'Change of plans',
       'Wrong Address'], dtype=object)

In [32]:
df['Incomplete Rides Reason'].unique()

array(['Na', 'Vehicle Breakdown', 'Other Issue', 'Customer Demand'],
      dtype=object)

In [35]:
df['Incomplete Rides'].unique()

array([0., 1.])

In [40]:
#Replacing null values

df['Avg VTAT'] = df['Avg VTAT'].fillna(0)
df['Avg CTAT'] = df['Avg CTAT'].fillna(0)
df['Incomplete Rides'] = df['Incomplete Rides'].fillna(0)
df['Incomplete Rides Reason'] = df['Incomplete Rides Reason'].fillna("Na")
df['Payment Method'] = df['Incomplete Rides Reason'].fillna("No Payment Made")
df['Incomplete Rides'] = df['Incomplete Rides'].astype(bool)
df['Booking Value'] = df['Booking Value'].fillna(0)
df['Ride Distance'] = df['Ride Distance'].fillna(0)

In [41]:
df.to_csv("data_cleaned.csv")

In [42]:
df1 = pd.read_csv('data_cleaned.csv')
df1.head()

,Unnamed: 0,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,...,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Dates,xTime
0,0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,0.0,...,NaN,False,Na,0.0,0.00,NaN,NaN,Na,2024-03-23,2025-08-16 12:29:38
1,1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,...,NaN,True,Vehicle Breakdown,237.0,5.73,NaN,NaN,Vehicle Breakdown,2024-11-29,2025-08-16 18:01:39
2,2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,...,NaN,False,Na,627.0,13.58,4.9,4.9,Na,2024-08-23,2025-08-16 08:56:10
3,3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,...,NaN,False,Na,416.0,34.02,4.6,5.0,Na,2024-10-21,2025-08-16 17:17:25
4,4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,...,NaN,False,Na,737.0,48.21,4.1,4.3,Na,2024-09-16,2025-08-16 22:08:00